### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by pochoi** [mweastwood/LibHealpix.jl#10]
Just a warning to all OSX users. 

Currently this wrapper is not working on OSX. It is because gcc/g++ in OSX is actually clang which does not support some flags used in building Healpix 3.20.

Healpy (the python wrapper) is working on OSX. and, in Homebrew, Healpix 3.30 can be built using autoconf. I guess there should be some ways to fix this wrapper so that it is OSX compatible. Good luck.

Here maybe some possible ways which might work.
- Link gcc/g++ to the GNU gcc installed by Homebrew
- Don't build Healpix by yourself. Build Healpix by Homebrew.

**Comment by mweastwood** [comment]
Yes the build system is incredibly brittle right now so I'm not at all surprised by this. I'll try to borrow an OSX machine and see what I can come up with.

**Comment by pochoi** [comment]
#11 Here is how I build the package in OSX. I just change some types and path so that it can be built by GNU gcc in OSX.

In OSX, Healpix can be installed by Homebrew. What Homebrew does is quite simple. It just call autoconf to do the configuration. Maybe the Healpix library in package should be updated to 3.30 and built using autoconf.
